stages:
  - deploy

variables:
  KUBE_NAMESPACE: "monitoring"

deploy_prometheus_grafana:
  stage: deploy
  image: alpine/k8s:1.21.0
  script:
    - apk add --no-cache curl
    - curl -LO https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
    - tar -zxvf helm-v3.5.4-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
    - helm upgrade --install prometheus prometheus-community/prometheus --namespace $KUBE_NAMESPACE --create-namespace
    - helm upgrade --install grafana grafana/grafana --namespace $KUBE_NAMESPACE --create-namespace
  only:
    - main
