---
- name: Upgrade Kubernetes Cluster from 1.27 to 1.28
  hosts: all
  become: yes
  tasks:
    - name: Unhold kubelet, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: unhold

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade kubeadm to 1.28
      apt:
        name: kubeadm=1.28.0-00
        state: present
        
    - name: Perform kubeadm upgrade node
      command: kubeadm upgrade node
      when: "'master' in group_names or 'worker' in group_names"

    - name: Drain node1 before upgrade
      command: kubectl drain worker1 --ignore-daemonsets --delete-local-data
      
      - name: Drain node2 before upgrade
      command: kubectl drain worker2 --ignore-daemonsets --delete-local-data
   

    - name: Upgrade kubelet and kubectl to 1.28
      apt:
        name:
          - kubelet=1.28.0-00
          - kubectl=1.28.0-00
        state: present

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

    - name: Uncordon node1 after upgrade
      command: kubectl uncordon worker1
      
    - name: Uncordon node2 after upgrade
      command: kubectl uncordon worker2
  

    - name: Hold kubelet, kubeadm and kubectl at version 1.28
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: hold

    - name: Check nodes status
      command: kubectl get nodes
      register: kubectl_get_nodes
      when: "'master' in group_names"
    


- name: Upgrade Kubernetes Cluster from 1.28 to 1.29
  hosts: all
  become: yes
  tasks:
    - name: Unhold kubelet, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: unhold

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade kubeadm to 1.29
      apt:
        name: kubeadm=1.29.0-00
        state: present
        
    - name: Perform kubeadm upgrade node
      command: kubeadm upgrade node
      when: "'master' in group_names or 'worker' in group_names"

    - name: Drain node1 before upgrade
      command: kubectl drain worker1 --ignore-daemonsets --delete-local-data
      
      - name: Drain node2 before upgrade
      command: kubectl drain worker2 --ignore-daemonsets --delete-local-data
   

    - name: Upgrade kubelet and kubectl to 1.29
      apt:
        name:
          - kubelet=1.29.0-00
          - kubectl=1.29.0-00
        state: present

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

    - name: Uncordon node1 after upgrade
      command: kubectl uncordon worker1
      
    - name: Uncordon node2 after upgrade
      command: kubectl uncordon worker2
  

    - name: Hold kubelet, kubeadm and kubectl at version 1.28
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: hold

    - name: Check nodes status
      command: kubectl get nodes
      register: kubectl_get_nodes
      when: "'master' in group_names"



- name: Upgrade Kubernetes Cluster from 1.29 to 1.30
  hosts: all
  become: yes
  tasks:
    - name: Unhold kubelet, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: unhold

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade kubeadm to 1.30
      apt:
        name: kubeadm=1.30.0-00
        state: present
        
    - name: Perform kubeadm upgrade node
      command: kubeadm upgrade node
      when: "'master' in group_names or 'worker' in group_names"

    - name: Drain node1 before upgrade
      command: kubectl drain worker1 --ignore-daemonsets --delete-local-data
      
      - name: Drain node2 before upgrade
      command: kubectl drain worker2 --ignore-daemonsets --delete-local-data
   

    - name: Upgrade kubelet and kubectl to 1.30
      apt:
        name:
          - kubelet=1.30.0-00
          - kubectl=1.30.0-00
        state: present

    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted

    - name: Uncordon node1 after upgrade
      command: kubectl uncordon worker1
      
    - name: Uncordon node2 after upgrade
      command: kubectl uncordon worker2
  

    - name: Hold kubelet, kubeadm and kubectl at version 1.30
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        mark: hold

    - name: Check nodes status
      command: kubectl get nodes
      register: kubectl_get_nodes
      when: "'master' in group_names"

